### ISSUE TITLE
Installing fpp-brightness

### ISSUE THREAD

**Issue by jamondouglas** [FalconChristmas/fpp-brightness#1]
I was using the fpp-brightness plugin with out any issue a few weeks ago. Today when I installed and started using the plugin, I received a ```NOT FOUND``` message when accessing the rest api at http:/fpp/api/plugin-apis/Brightness/100. I connected to the docker container running the fpp instance and found this in the install log. Can you advise?

![image](https://user-images.githubusercontent.com/4206162/66086636-80de8f80-e529-11e9-986f-e027729ae4b5.png)

**Comment by dkulp** [comment]
Are you sure you are on FPP 3.2 or 3.3?   That looks like you have an earlier version of FPP.

**Comment by jamondouglas** [comment]
Ok, I will update my image version and see if I get a new result.

**Comment by jamondouglas** [comment]
@dkulp that was definitely the issue. I updated the fpp version to 3.3 and the plugin works. My only issue is when I change the brightness via the url or plugin web page, the animation that is being played blinks on and off until I set the brightness back to 100. Is this expected behavior?

**Comment by jamondouglas** [comment]
I have just pulled the latest docker image that has been published to the fpp repo. The issue I reported above seems to be fixed using the latest version so I will close this issue out.
